### PR TITLE
Switch to official model implementation

### PR DESCRIPTION
**Pull request by djwessel**
The WIP ydshieh model has been deprecated https://huggingface.co/ydshieh/kosmos-2-patch14-224. This change switches to the official implementation from Microsoft.

Addresses #3

### CODE REVIEW

**Comment by djwessel** [comment]
@capjamesg Anything I can do to help move this along?

**Review by capjamesg — APPROVED** [review]
Looks good.

**Comment by capjamesg** [comment]
Thank you for your contribution! I didn't realize the WIP `ydshieh` model was deprecated. Thank you for moving this package to use the official model. I don't have time to do a PyPi release today, but I will release an update this week.

**Comment by capjamesg** [comment]
I have published a new release of Autodistill Kosmos2. You can use it using `pip install --upgrade autodistill-kosmos-2`.

**Pull request merged**
